# Generated by Django 5.1.6 on 2025-02-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='name',
        ),
    ]
