# Generated by Django 5.1.6 on 2025-02-23 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_gokart_remove_booking_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gokart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.gokart'),
        ),
    ]
