# Generated by Django 5.1.6 on 2025-02-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking_gokart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gokart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.gokart'),
        ),
    ]
