# Generated by Django 5.1.6 on 2025-02-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_booking_customer_alter_booking_gokart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='gokart',
        ),
        migrations.AddField(
            model_name='booking',
            name='gokarts',
            field=models.ManyToManyField(to='app.gokart'),
        ),
    ]
