# Generated by Django 5.1.6 on 2025-02-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_booking_gokart_booking_gokarts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='gokarts',
            field=models.ManyToManyField(null=True, to='app.gokart'),
        ),
    ]
