# Generated by Django 5.1.6 on 2025-02-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_booking_gokarts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='gokarts',
            field=models.ManyToManyField(blank=True, null=True, to='app.gokart'),
        ),
    ]
