# Generated by Django 5.1.6 on 2025-02-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_booking_gokarts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='gokarts',
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking')),
                ('gokart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gokart')),
            ],
        ),
    ]
